################################################################################
# This script saves the ouput from wildfire/RX modeling. This is part of the C-BREC Fire Module.
#
# tile_number: numeric tile number.
#
# Author: Micah Wright, Humboldt State University
################################################################################

save_output <- function(dt,
                        Silvicultural_Treatment,
                        ID,
                        Burn_Type,
                        tile_number,
                        Fraction_Piled,
                        Fraction_Scattered,
                        Biomass_Collection,
                        Pulp_Market,
                        secondary_burn,
                        year,
                        path_em,
                        path_res) {
        
        emissions_df <- dt[, list(x, 
                                  y,
                                  fuelbed_number,
                                  FCID2018,
                                  ID,
                                  Silvicultural_Treatment,
                                  Burn_Type,
                                  Fraction_Piled,
                                  Fraction_Scattered,
                                  Biomass_Collection,
                                  Pulp_Market = Pulp_Market,
                                  Secondary_Burn = secondary_burn,
                                  Year,
                                  total_except_pile_char,
                                  total_except_pile_CH4,
                                  total_except_pile_CO,
                                  total_except_pile_CO2,
                                  total_except_pile_NOx,
                                  total_except_pile_PM10,
                                  total_except_pile_PM2.5,
                                  total_except_pile_SO2,
                                  total_except_pile_VOC,
                                  total_pile_clean_PM10, 
                                  total_pile_vdirty_PM10,
                                  total_pile_clean_PM2.5,
                                  total_pile_vdirty_PM2.5, 
                                  total_pile_CH4,
                                  total_pile_CO,
                                  total_pile_CO2,              
                                  total_pile_NOx,
                                  total_pile_SO2,
                                  total_pile_VOC,
                                  pile_char,
                                  char_fwd_residue,
                                  char_cwd_residue,
                                  total_duff_exposed,
                                  total_foliage_exposed,
                                  total_fwd_exposed,
                                  total_cwd_exposed,
                                  total_fuel_consumed, 
                                  total_pile_consumed,
                                  total_duff_consumed,
                                  total_foliage_consumed,
                                  total_fwd_consumed,
                                  total_cwd_consumed,
                                  total_duff_residue_CH4,      
                                  total_foliage_residue_CH4,
                                  total_fwd_residue_CH4,
                                  total_cwd_residue_CH4,    
                                  total_duff_residue_CO,
                                  total_foliage_residue_CO,
                                  total_fwd_residue_CO,
                                  total_cwd_residue_CO,
                                  total_duff_residue_CO2,
                                  total_foliage_residue_CO2,
                                  total_fwd_residue_CO2,
                                  total_cwd_residue_CO2,
                                  total_duff_residue_NOx,
                                  total_foliage_residue_NOx,
                                  total_fwd_residue_NOx,
                                  total_cwd_residue_NOx,
                                  total_duff_residue_PM10,
                                  total_foliage_residue_PM10,
                                  total_fwd_residue_PM10,
                                  total_cwd_residue_PM10,
                                  total_duff_residue_PM2.5,
                                  total_foliage_residue_PM2.5,
                                  total_fwd_residue_PM2.5,
                                  total_cwd_residue_PM2.5,
                                  total_duff_residue_SO2,
                                  total_foliage_residue_SO2,
                                  total_fwd_residue_SO2,
                                  total_cwd_residue_SO2,
                                  total_duff_residue_VOC,
                                  total_foliage_residue_VOC,
                                  total_fwd_residue_VOC,
                                  total_cwd_residue_VOC)]
        
        residual_df <- dt[, list(x,
                                 y,
                                 fuelbed_number,
                                 FCID2018,
                                 ID,
                                 Silvicultural_Treatment,
                                 Burn_Type,
                                 Fraction_Piled,
                                 Fraction_Scattered,
                                 Biomass_Collection,
                                 Pulp_Market = Pulp_Market,
                                 Secondary_Burn = secondary_burn,
                                 Year,
                                 Slope,
                                 Fm10,
                                 Fm1000,
                                 Wind_corrected,
                                 duff_upper_loading,
                                 litter_loading,
                                 one_hr_sound,
                                 ten_hr_sound,
                                 hun_hr_sound,
                                 oneK_hr_sound,
                                 oneK_hr_rotten,
                                 tenK_hr_sound,
                                 tenK_hr_rotten,
                                 tnkp_hr_sound,
                                 tnkp_hr_rotten,
                                 pile_load)]
        
        ## Workflow to convert data from floating point decimal to integer with minimal data loss ##
        # convert us short tons/acre to grams per acre
        # output of fire model will be in grams
        # short ton * 907185 grams/short tons = grams
        # round to nearest whole number
        # convert to integer
        
        emissions_df[,':='(total_except_pile_char = as.integer(round(total_except_pile_char * 907185, digits = 0)),
                           total_except_pile_CH4 = as.integer(round(total_except_pile_CH4 * 907185, digits = 0)),
                           total_except_pile_CO = as.integer(round(total_except_pile_CO * 907185, digits = 0)),
                           total_except_pile_CO2 = as.integer(round(total_except_pile_CO2 * 907185, digits = 0)),
                           total_except_pile_NOx = as.integer(round(total_except_pile_NOx * 907185, digits = 0)),
                           total_except_pile_PM10 = as.integer(round(total_except_pile_PM10 * 907185, digits = 0)),
                           total_except_pile_PM2.5 = as.integer(round(total_except_pile_PM2.5 * 907185, digits = 0)),
                           total_except_pile_SO2 = as.integer(round(total_except_pile_SO2 * 907185, digits = 0)),
                           total_except_pile_VOC = as.integer(round(total_except_pile_VOC * 907185, digits = 0)),
                           total_pile_clean_PM10 = as.integer(round(total_pile_clean_PM10 * 907185, digits = 0)),
                           total_pile_vdirty_PM10 = as.integer(round(total_pile_vdirty_PM10 * 907185, digits = 0)),
                           total_pile_clean_PM2.5 = as.integer(round(total_pile_clean_PM2.5 * 907185, digits = 0)),
                           total_pile_vdirty_PM2.5 = as.integer(round(total_pile_vdirty_PM2.5 * 907185, digits = 0)),
                           total_pile_CH4 = as.integer(round(total_pile_CH4 * 907185, digits = 0)),
                           total_pile_CO = as.integer(round(total_pile_CO * 907185, digits = 0)),
                           total_pile_CO2 = as.integer(round(total_pile_CO2 * 907185, digits = 0)),
                           total_pile_NOx = as.integer(round(total_pile_NOx * 907185, digits = 0)),
                           total_pile_SO2 = as.integer(round(total_pile_SO2 * 907185, digits = 0)),
                           total_pile_VOC = as.integer(round(total_pile_VOC * 907185, digits = 0)),
                           pile_char = as.integer(round(pile_char * 907185, digits = 0)),
                           total_duff_exposed = as.integer(round(total_duff_exposed * 907185, digits = 0)),
                           total_foliage_exposed = as.integer(round(total_foliage_exposed * 907185, digits = 0)),
                           total_fwd_exposed = as.integer(round(total_fwd_exposed * 907185, digits = 0)),
                           total_cwd_exposed = as.integer(round(total_cwd_exposed * 907185, digits = 0)),
                           total_fuel_consumed = as.integer(round(total_fuel_consumed * 907185, digits = 0)),
                           total_pile_consumed = as.integer(round(total_pile_consumed * 907185, digits = 0)),
                           total_duff_consumed = as.integer(round(total_duff_consumed * 907185, digits = 0)),
                           total_foliage_consumed = as.integer(round(total_foliage_consumed * 907185, digits = 0)),
                           total_fwd_consumed = as.integer(round(total_fwd_consumed * 907185, digits = 0)),
                           total_cwd_consumed = as.integer(round(total_cwd_consumed * 907185, digits = 0)),
                           char_fwd_residue = as.integer(round(char_fwd_residue * 907185, digits = 0)),
                           char_cwd_residue = as.integer(round(char_cwd_residue * 907185, digits = 0)),
                           total_duff_residue_CH4 = as.integer(round(total_duff_residue_CH4 * 907185, digits = 0)),
                           total_foliage_residue_CH4 = as.integer(round(total_foliage_residue_CH4 * 907185, digits = 0)),
                           total_fwd_residue_CH4 = as.integer(round(total_fwd_residue_CH4 * 907185, digits = 0)),
                           total_cwd_residue_CH4 = as.integer(round(total_cwd_residue_CH4 * 907185, digits = 0)),
                           total_duff_residue_CO = as.integer(round(total_duff_residue_CO * 907185, digits = 0)),
                           total_foliage_residue_CO = as.integer(round(total_foliage_residue_CO * 907185, digits = 0)),
                           total_fwd_residue_CO = as.integer(round(total_fwd_residue_CO * 907185, digits = 0)),
                           total_cwd_residue_CO = as.integer(round(total_cwd_residue_CO * 907185, digits = 0)),
                           total_duff_residue_CO2 = as.integer(round(total_duff_residue_CO2 * 907185, digits = 0)),
                           total_foliage_residue_CO2 = as.integer(round(total_foliage_residue_CO2 * 907185, digits = 0)),
                           total_fwd_residue_CO2 = as.integer(round(total_fwd_residue_CO2 * 907185, digits = 0)),
                           total_cwd_residue_CO2 = as.integer(round(total_cwd_residue_CO2 * 907185, digits = 0)),
                           total_duff_residue_NOx = as.integer(round(total_duff_residue_NOx * 907185, digits = 0)),
                           total_foliage_residue_NOx = as.integer(round(total_foliage_residue_NOx * 907185, digits = 0)),
                           total_fwd_residue_NOx = as.integer(round(total_fwd_residue_NOx * 907185, digits = 0)),
                           total_cwd_residue_NOx = as.integer(round(total_cwd_residue_NOx * 907185, digits = 0)),
                           total_duff_residue_PM10 = as.integer(round(total_duff_residue_PM10 * 907185, digits = 0)),
                           total_foliage_residue_PM10 = as.integer(round(total_foliage_residue_PM10 * 907185, digits = 0)),
                           total_fwd_residue_PM10 = as.integer(round(total_fwd_residue_PM10 * 907185, digits = 0)),
                           total_cwd_residue_PM10 = as.integer(round(total_cwd_residue_PM10 * 907185, digits = 0)),
                           total_duff_residue_PM2.5 = as.integer(round(total_duff_residue_PM2.5 * 907185, digits = 0)),
                           total_foliage_residue_PM2.5 = as.integer(round(total_foliage_residue_PM2.5 * 907185, digits = 0)),
                           total_fwd_residue_PM2.5 = as.integer(round(total_fwd_residue_PM2.5 * 907185, digits = 0)),
                           total_cwd_residue_PM2.5 = as.integer(round(total_cwd_residue_PM2.5 * 907185, digits = 0)),
                           total_duff_residue_SO2 = as.integer(round(total_duff_residue_SO2 * 907185, digits = 0)),
                           total_foliage_residue_SO2 = as.integer(round(total_foliage_residue_SO2 * 907185, digits = 0)),
                           total_fwd_residue_SO2 = as.integer(round(total_fwd_residue_SO2 * 907185, digits = 0)),
                           total_cwd_residue_SO2 = as.integer(round(total_cwd_residue_SO2 * 907185, digits = 0)),
                           total_duff_residue_VOC = as.integer(round(total_duff_residue_VOC * 907185, digits = 0)),
                           total_foliage_residue_VOC = as.integer(round(total_foliage_residue_VOC * 907185, digits = 0)),
                           total_fwd_residue_VOC = as.integer(round(total_fwd_residue_VOC * 907185, digits = 0)),
                           total_cwd_residue_VOC = as.integer(round(total_cwd_residue_VOC * 907185, digits = 0))
        )]
        
        residual_df <- dt[, ":="(duff_upper_loading = as.integer(round(duff_upper_loading * 907185, digits = 0)),
                                 litter_loading = as.integer(round(litter_loading * 907185, digits = 0)),
                                 one_hr_sound = as.integer(round(one_hr_sound * 907185, digits = 0)),
                                 ten_hr_sound = as.integer(round(ten_hr_sound * 907185, digits = 0)),
                                 hun_hr_sound = as.integer(round(hun_hr_sound * 907185, digits = 0)),
                                 oneK_hr_sound = as.integer(round(oneK_hr_sound * 907185, digits = 0)),
                                 oneK_hr_rotten = as.integer(round(oneK_hr_rotten * 907185, digits = 0)),
                                 tenK_hr_sound = as.integer(round(tenK_hr_sound * 907185, digits = 0)),
                                 tenK_hr_rotten = as.integer(round(tenK_hr_rotten * 907185, digits = 0)),
                                 tnkp_hr_sound = as.integer(round(tnkp_hr_sound * 907185, digits = 0)),
                                 tnkp_hr_rotten = as.integer(round(tnkp_hr_rotten * 907185, digits = 0)),
                                 pile_load = as.integer(round(pile_load * 907185, digits = 0)))]
        
        # End truncating for as.integer

        
        # save output with changes
        
        saveRDS(emissions_df,
                file = paste0(path_em,
                              tile_number,
                              "/",
                              paste(Silvicultural_Treatment,
                                    Burn_Type,
                                    Fraction_Piled,
                                    Fraction_Scattered,
                                    secondary_burn,
                                    Biomass_Collection,
                                    Pulp_Market,
                                    ID,
                                    tile_number,
                                    year, 
                                    sep = "-"),
                              ".rds"))
        

        saveRDS(residual_df,
                file = paste0(path_res,
                              tile_number,
                              "/",
                              paste(Silvicultural_Treatment,
                                    Burn_Type,
                                    Fraction_Piled,
                                    Fraction_Scattered,
                                    secondary_burn,
                                    Biomass_Collection,
                                    Pulp_Market,
                                    ID,
                                    tile_number,
                                    year,
                                    sep = "-"),
                              ".rds"))
}